// exportamos todas las acciones para poderlas usar en 
//action reducer sagas y el componente 

export const FETCH_COLUMN_RANDOM_START = 'FETCH_COLUMN_RANDOM_START';
export const FETCH_COLUMN_RANDOM_SUCCESS = 'FETCH_COLUMN_RANDOM_SUCCESS';
export const FETCH_COLUMN_RANDOM_FAILED = 'FETCH_COLUMN_RANDOM_FAILED';

export const GET_LIST_PROJECTS_START = 'GET_LIST_PROJECTS_START';
export const GET_LIST_PROJECTS_SUCCESS = 'GET_LIST_PROJECTS_SUCCESS';
export const GET_LIST_PROJECTS_FAILED = 'GET_LIST_PROJECTS_FAILED';

export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';

export const GET_TASK_LIST_START = 'GET_TASK_LIST_START';
export const GET_TASK_LIST_SUCCESS = 'GET_TASK_LIST_SUCCESS';
export const GET_TASK_LIST_FAILED = 'GET_TASK_LIST_FAILED';